Don't crash if alsa_snd_pcm_poll_descriptors fails
PortAudio/portaudio pull request #344
Opened 2020-11-11 23:28 UTC by daschuer

This fixes #268 

This patch was original proposed by Chameleon here: 
https://portaudio.music.columbia.narkive.com/3V9hsUak/pa-linux-alsa-c-3636-assertion-failed-with-hack-fix

2020-11-19 02:09 UTC, philburk requested changes
I will review the rest in more detail.

2020-11-19 02:09 UTC, philburk commented on src/hostapi/alsa/pa_linux_alsa.c
>      (void)ret;  /* Prevent unused variable warning if asserts are turned off */
Can remove (void) cast because we use ret.

2020-12-06 17:11 UTC, philburk approved these changes
This has been discussed and approved by several people on the mail list.

2020-12-08 08:01 UTC, RossBencina commented
I don't feel qualified to comment on this.

2020-12-14 01:05 UTC, philburk requested changes
I faked an xrun in pa_linux_alsa.c at line 3645 with:

    static int count = 0;
    if( ret != self->nfds || ((count++ % 173) == 150)) // FIXME fake an error

Then I tried running the test paex_read_write_wire and it failed.
But the test aborts when it gets an xrun.
So I modified the test to just print a message when ReadStream or WriteStream return an error.
Now for every xrun I trigger in pa_alsa I get a flood of error returns.

2020-12-14 01:05 UTC, philburk commented on src/hostapi/alsa/pa_linux_alsa.c
> +            int res = PaAlsaStreamComponent_BeginPolling( &self->playback, playbackPfds );
If this change is needed here then would it not also be needed on line 3808?

2020-12-14 07:27 UTC, daschuer commented
Done

2020-12-18 17:54 UTC, philburk commented on src/hostapi/alsa/pa_linux_alsa.c
> +            int res = PaAlsaStreamComponent_BeginPolling( &self->playback, playbackPfds );
Thanks for the change.

2020-12-18 17:56 UTC, philburk approved these changes

2020-12-18 17:57 UTC, philburk commented
Fixes #268

2020-12-18 17:57 UTC, merged

2020-12-23 19:32 UTC, antiochtech commented
im still getting the error so i suspect my project is still using the old version. its a python project using the raspbian package python3-pyaudio. ive followed the installation recommendations for my device (https://github.com/PortAudio/portaudio/wiki/Platforms_RaspberryPi and http://portaudio.com/docs/v19-doxydocs/compile_linux.html), but i suspect theres another step?