Set macOS version minimum to 10.6 if using the macOS 11.0 SDK
PortAudio/portaudio pull request #359
Opened 2020-12-01 18:50 UTC by hoolrory

Required for using the changes made in #338, to get things working on macOS 11.0

For #218

2020-12-05 23:51 UTC, philburk approved these changes
Thanks

2020-12-05 23:57 UTC, philburk requested changes
Wait. I just realized that the file "configure" should not be edited directly.
The edits should be made in "configure.in" and then "configure" is auto-generated.

See #317 for an example.
If you want, I can generate the files based on your idea. I have the tools installed on Linux.

2020-12-21 15:32 UTC, jmelas commented
Please note that current version of the SDK is 11.1 so we also need to add support for that!

2020-12-21 15:37 UTC, jmelas commented
Another idea which may help:
`xcrun --sdk macosx --show-sdk-version`
will display the sdk installed

2021-01-14 16:39 UTC, Be-ing commented
Obsoleted by #434

2021-01-21 14:50 UTC, Be-ing commented
I don't know what the right way to fix this is, but this is a great example of why autogenerated files should not be committed to version control.

2021-01-25 00:43 UTC, Be-ing commented
Superseded by #470

2021-01-25 01:45 UTC, philburk commented
@hoolrory - I see that you also added "arm64".
Was that to add support for the new ARM Macs?
If so then we should add that after #470 in a separate PR.

2021-01-25 16:06 UTC, philburk commented
Closing in favor of #470, which updates configure.in

2021-01-25 16:06 UTC, closed without merging

2021-02-01 19:34 UTC, Be-ing commented
@hoolrory Do you have an M1 Mac? If so, can you please test #489? We need someone who has M1 hardware to confirm it works.