fix signed/unsigned mismatch warning
PortAudio/portaudio pull request #376
Opened 2020-12-18 15:41 UTC by jmelas

In file pa_win_wasapi.c we compare signed SystemTimer::granularity with unsigned TIMECAPS::wPeriodMin.
This PR resolves the issue.

2020-12-22 05:24 UTC, RossBencina reviewed
Comparing with cast and then assigning without cast on the following line looks incorrect to me. At least use a cast on both lines.

2020-12-22 09:05 UTC, jmelas commented
assignment does implicit conversion

2020-12-27 13:03 UTC, RossBencina commented
Ok by me.

2020-12-28 00:46 UTC, philburk approved these changes

2020-12-29 09:59 UTC, dmitrykos requested changes
@jmelas, would you please revert the last change back to d4744e7381d9681aa799b07494e787215ff2beac. We really do not need an additional variable here as it bloats the code.

2020-12-29 10:27 UTC, dmitrykos commented
Implicit conversion is ok in this case and does not lead to a compiler warning in my case but if there is something wrong with it would you please comment.

2020-12-29 14:45 UTC, jmelas commented
@dmitrykos I agree with you but this is a change requested by @RossBencina and I would not like to go back and forth,
so let's hear @philburk and @RossBencina thoughts on this.

2020-12-29 15:17 UTC, dmitrykos commented
> At least use a cast on both lines

@jmelas we can follow this proposal of @RossBencina, e.g. just add an explicit cast inside the assignment like this:

```c
if (timer->granularity < (INT32)caps.wPeriodMin)
    timer->granularity = (INT32)caps.wPeriodMin;
```

Dangling temporary variable just for an assignment looks too bulky to me. Also your commits need to be squashed into one to be merged succesfully.

2020-12-29 15:22 UTC, jmelas commented
Done thanks!

2020-12-29 15:30 UTC, dmitrykos approved these changes
Looks great, thank you very much!

2020-12-29 15:30 UTC, merged