dsound: Fix warning of redefining _WIN32_WINNT when compiling with GCC/MinGW
PortAudio/portaudio pull request #667
Opened 2021-11-18 19:21 UTC by dmitrykos

The warning is thrown as follows:
```c
[  5%] Building C object CMakeFiles/PortAudio.dir/src/hostapi/dsound/pa_win_ds.c.obj
pa_win_ds.c:54: warning: "_WIN32_WINNT" redefined
   54 | #define _WIN32_WINNT 0x0400 /* required to get waitable timer APIs */
      |
<command-line>: note: this is the location of the previous definition
```

`_WIN32_WINNT` is defined by GCC/MinGW and therefore it has to be checked before defining to 0x0400. If `_WIN32_WINNT` is defined to a lower value it will be redefined to 0x0400, therefore the expected behavior is preserved.

Closes #549

2021-11-23 16:36 UTC, jmelas requested changes
I think this define could be removed completely.
We don't support windows lower than NT4 do we?

2021-12-02 01:33 UTC, RossBencina commented
Looks ok, but please move the updated code at the top of the file, as Phil and I already requested  in #549

2021-12-02 08:22 UTC, dmitrykos commented
@RossBencina, done!

2021-12-09 01:09 UTC, philburk approved these changes

2021-12-09 01:09 UTC, RossBencina approved these changes

2021-12-09 01:10 UTC, merged

2021-12-09 09:01 UTC, jmelas commented
I am surprised this was merged.
_WIN32_WINNT should not be defined in code. It should be defined in the build settings.
Both in configure and CMake build settings we already define _WIN32_WINNT=0x0501
So I still believe that this define
#define _WIN32_WINNT 0x0400 /* required to get waitable timer APIs */
should have been removed completely.

2021-12-09 10:04 UTC, dmitrykos commented
@jmelas, another PR can remove this `ifdef` section. This one was closing #549 as per its discussion. I agree that this guard clause `#define _WIN32_WINNT 0x0400` may not be needed because min. Windows version that supports DS is Windows 95 (0x0400) anyway.

2021-12-12 01:47 UTC, philburk commented
@jmelas - Can you please review and comment on #676 ?