dsound: clamp input buffer size at 62.5 ms
PortAudio/portaudio pull request #782
Opened 2023-03-06 20:40 UTC by dechamps

This PR works around a DirectSound limitation where input host buffer sizes smaller than 31.25 ms are basically unworkable and make PortAudio hang. The workaround is to impose a minimal buffer size of 2*31.25 ms on input-only and full-duplex streams. This is enough for the read cursor to advance twice around the buffer, basically resulting in de facto double buffering.

This change was tested with `paloopback` under a wide variety of half/full-duplex, framesPerBuffer, and suggested latency parameters. (Note the testing was done on top of #772 as otherwise paloopback is not usable.)

In addition, this PR includes a small refactoring of the DirectSound buffer calculation code which was giving me headaches as I was working on the fix.

Fixes #775

2023-03-21 00:33 UTC, RossBencina commented
> This change was tested ...

@dechamps please could you update the PR description with information about which OS version(s) and audio devices were used for your testing. This gives us traceability if someone wants to compare your results later.

2023-03-21 02:01 UTC, RossBencina commented
Based on my testing reported at #775, I can get stable bidirectional audio with a 5.3ms input buffer size no problems with standard Realtek motherboard sound. I do get stalling with low output buffer sizes, so maybe there *is* a bug, but I don't think we have characterized it correctly yet. In any case with the available information, I don't think it's appropriate to put a blanket clamp to 31ms. I think we should continue the root-cause analysis at #775.

If it were the case that there are no systems where lower input buffer size works, or there was a way to detect that we were on such a system where the buffer limit applied, then the clamp would make total sense.

While I'm all for quirk workarounds, my take is that there will always be "low" latency/buffer settings which will produce unreliable output on some or all systems with some or all host APIs. It's up to the end user to tweak the buffering for best performance on their system. And that includes discovering the system limits. In other words, we should allow for parameter tuning beyond functioning limits. This PR prevents that.

If your goal is to provide a "foolproof" configuration (like clamping) that never fails due to quirks of some devices, then that logic should be put in the application code. (i.e. the application implements the clamp). PortAudio already provides the infrastructure to support this in `PaDeviceInfo`:
https://github.com/PortAudio/portaudio/blob/68e963a990da19bb013133dcbad59c2ed8ea0cf9/include/portaudio.h#L510-L515

It might make sense to update these `default` latency values to reflect the current findings.

2023-03-21 10:24 UTC, dechamps commented
> Based on my testing reported at #775, I can get stable bidirectional audio with a 5.3ms input buffer size no problems with standard Realtek motherboard sound. I do get stalling with low output buffer sizes, so maybe there _is_ a bug, but I don't think we have characterized it correctly yet. In any case with the available information, I don't think it's appropriate to put a blanket clamp to 31ms. I think we should continue the root-cause analysis at #775.

I just commented on #775 to show you that you did precisely reproduce the problem I characterized. Given the various indications that this is a widespread problem, and no evidence that there exists systems that *aren't* affected, I would say the blanket clamp is appropriate.

> If it were the case that there are no systems where lower input buffer size works

[It certainly looks like it](https://github.com/PortAudio/portaudio/issues/775#issuecomment-1449027828). And you can add your own system to that list since you did reproduce it.

> It's up to the end user to tweak the buffering for best performance on their system. And that includes discovering the system limits. In other words, we should allow for parameter tuning beyond functioning limits. This PR prevents that.
> 
> If your goal is to provide a "foolproof" configuration that never fails due to quirks of some devices (by clamping even if it degrades latency on some system), then that logic should be put in the application code.

If this failure mode merely resulted in glitchy audio, then I would agree (for example this is why I closed #788 instead of trying to implement a clamp in MME). However the failure mode we're dealing with here is much worse - it doesn't just cause glitchy audio, instead it results in a stall which is impossible to recover from and can easily compromise the stability of the application (deadlock), forcing the user to kill the app and restart it. I don't think this is acceptable behaviour from any library under any circumstances, regardless of parameters.

2023-03-22 01:24 UTC, mirh commented
Isn't there somebody you forgot to ask?
(*cue XP*, especially given that's presumably the major use case for dsound)

2023-03-22 22:44 UTC, mirh commented
> Do you have evidence that https://github.com/PortAudio/portaudio/issues/775 does not apply to XP?

Not really. 
But it would still seem almost impossible tbf?
It's not just that some functions may have been rewritten (or abstracted to wasapi), in your usual XP machine a lot of of the [processing](https://web.archive.org/web/20071002101652/http://forums.creative.com/creativelabs/board/message?board.id=Vista&message.id=1694) was up to the audio driver itself. 
So even going from a realtek to an nforce to a xfi could give you pretty different "low level" results. 

> I don't think it's fair to assume that users are using DS primarily to be compatible with XP.

My judgement was just theoretical, idk about history or implementation quirks. 
Of course not all shortcomings may matter to certain use case, but it seems pretty obvious that it is a deprecated second-tier api.

2023-03-22 23:26 UTC, dechamps commented
> > Do you have evidence that #775 does not apply to XP?
> 
> Not really.
> But it would still seem almost impossible tbf?

Okay, fair enough. Given that #775 affecting pre-Vista Windows seems unlikely, and given that the buffer size clamp could plausibly hurt low-latency DS users who are still on XP, I have updated this PR to do a version check so that it is a no-op on pre-Vista Windows.

I think all concerns with this PR have been addressed now?

2023-03-28 00:38 UTC, RossBencina commented
My personal status: I want to do more local testing before I comment further.

2024-05-24 23:11 UTC, philburk requested changes

2024-05-24 23:12 UTC, RossBencina commented
As I understand it, #772 is blocking this, and I will look into that one.

2024-05-25 08:37 UTC, dechamps commented
> As I understand it, #772 is blocking this, and I will look into that one.

No, this PR does not depend on #772. #772 is only required if you want to test this PR using `paloopback`. This is because `paloopback` currently shows DirectSound as glitchy (correctly, I might add) due to #770, and #772 is the fix for that.

2024-05-25 19:28 UTC, dechamps commented on src/hostapi/dsound/pa_win_ds.c
> +    if( (windowsMajorVersion == 4) && (windowsMajorVersion == 2) )
Good catch. Actually this part of the PR has been made obsolete by 6ee9836a08d201c118b4715d4d70242816584000. Rebasing and resolving the resulting merge conflict made this change go away.

2025-01-05 09:42 UTC, JoergAtGithub commented
Is there a reason, why this priority 1 PR get not merged?

2025-01-17 00:04 UTC, RossBencina commented
> Is there a reason, why this priority 1 PR get not merged?

It is stuck waiting for me to have time to review it properly.

2025-02-07 03:59 UTC, RossBencina commented
This is my interim review, awaiting discussion with Phil. TLDR: for now no changes are requested. Phil and I need to decide whether to merge more-or-less as-is or require a different approach that doesn't add latency in the full-duplex case.

> clamp input buffer size at 62.5 ms

In fact the current PR clamps both input _and output_ buffer sizes to 62.5ms, except for output-only streams, where the buffer size follows the old calculations. The change is limited to Vista and later where the workaround is understood to be required.

I will take it at face value that it is necessary to clamp the input buffer size on some systems. I have not independently verified this. I have not encountered it myself, nor had it reported as a bug against my applications.

The substantive content of this PR is to add three lines to the end of `CalculateBufferSettings()`

```
    if( hasInput && PaWinUtil_GetOsVersion() >= paOsVersionWindowsVistaServer2008 )
    {
        *hostBufferSizeFrames = max( *hostBufferSizeFrames, 2 * 0.03125 * sampleRate );
    }
```

By performing this clamping in `CalculateBufferSettings()` the output buffer size will also be clamped (in the input+output case). I expect this will increase output latency beyond what is strictly necessary. Obviously that is undesirable. (Also obviously, without some kind of fix our code is not working as-is.)

Our implementation assumes the same buffer size for input and output, and I am not sure how easy it would be to adjust it to use different buffer sizes for input and output. Certainly the current PR seems like a safe approach whereas clamping only the input buffer size (to be different from the output buffer size) requires more careful analysis for possible problems.

---
> this PR includes a small refactoring of the DirectSound buffer calculation code which was giving me headaches as I was working on the fix.

As far as I'm concerned this PR includes a complete rewrite of the logic in `CalculateBufferSettings()`. The rewrite turns out to perform exactly the same calculations as the old code. Convincing myself of this fact was time I could have better spent elsewhere. Please be mindful that the ease of getting things merged is inversely proportional to the time it takes code review to verify that nothing was broken. 

I acknowledge that the existing code could be improved. For the purposes of this patch my preference is probably to keep the current code and just add the clamping patch at the end of the function. But let's not get into that now. No changes requested.

---

Conclusion: this is one of the few blockers for the 19.8 release and I think #775 is severe enough to warrant an imperfect fix. Ideally this fix would not have the side effect of adding latency in the input+output case, but that would most likely be a bigger and riskier change.

Phil and I will discuss this at our next review meeting (most likely morning February 21 Melbourne time).

2025-02-08 11:34 UTC, dechamps commented
> I will take it at face value that it is necessary to clamp the input buffer size on some systems. I have not independently verified this. I have not encountered it myself

You did independently verify this. In https://github.com/PortAudio/portaudio/issues/775#issuecomment-1477575640 I showed that you actually reproduced the issue, you just didn't realize it.

> By performing this clamping in `CalculateBufferSettings()` the output buffer size will also be clamped (in the input+output case). I expect this will increase output latency beyond what is strictly necessary. Obviously that is undesirable.

I'm not entirely sure that's true. I wrote this PR 2 years ago(!) so obviously my memory of how this works is rusty. But if my recollection is right, in the case of the DS (which uses a ring buffer with a cursor) the latency is not determined by the buffer size - it's determined by the polling period, and by the DS cursor granularity. That said I guess it's possible the effective DS cursor granularity could get coarser as the buffer size gets larger - I have not looked into this.

To be clear I have no plans to dig into this further. Properly following up on your review would require me to look back into this 2 years after the fact when I forgot almost everything about the context and how this particular piece of code works. Huge gaps like these make these back and forths very expensive in terms of context switching.

> As far as I'm concerned this PR includes a complete rewrite of the logic in `CalculateBufferSettings()`. The rewrite turns out to perform exactly the same calculations as the old code. Convincing myself of this fact was time I could have better spent elsewhere.

Ross, in my 20-year career as a software engineer, I believe you are literally the first person I came across who would complain in a code review that a contributor improved the readability of a piece of code. This is one of these moments where I can barely believe what I'm reading.

> Convincing myself of this fact was time I could have better spent elsewhere.

Deciphering how the original calculation worked so that I could write this fix is time I could have spent elsewhere. I had to spend the time to understand the calculation anyway, so once I understood it I thought I might as well take the opportunity to do everyone a favour and try to spare the next guy the same ordeal. Also known as "technical debt reduction".

In every other collaborative software project I worked on this kind of change would have been welcomed with open arms. But the more PRs I send to PA, the more I come to realize this project seems to be operating by some very strange rules that stand diametrically opposite to the rest of the industry. This may explain why there are so few contributions (especially in code you seem to have a personal interest in, Ross - PRs for other parts of PA seem to go a bit smoother).

This kind of interaction is definitely discouraging me from making any further contributions. I don't have any immediate plans to resume work I had planned around PA, but if I do I'm starting to feel like it would be best if I kept them in a private fork. I'm starting to get tired of the intense drama over every PR I send where real fixes for real problems are being blocked on incredibly silly nitpicks. Not to mention the turnaround time measured in literal years.

> For the purposes of this patch my preference is probably to keep the current code and just add the clamping patch at the end of the function.

There may have been some reason why I didn't do it that way - but honestly 2 years later I wouldn't be able to remember, so feel free to try that if you'd like.

Feel free to do with this PR what you will - as I said I don't have any plans to work on it any further.

2025-02-28 00:35 UTC, philburk commented
@dechamps - Thanks again for the PR. I think you have fixed an important bug with DirectSound input streams. You also contributed a cleanup in some nearby code. Both of these changes are helpful.

To reiterate what Ross said, we are not asking you to make any more changes. But we strongly prefer having bug fixes and refactoring in separate PRs if possible. We will either merge this as-is, or split it into a bug fix PR and a refactoring PR. We would like to get the bug fix in the next release.

Splitting it into smaller PRs makes it much easier to review each part, which also speeds up the process.

Another reason to keep bug fixes as small as possible is that it makes it easier to back-port a bug fix to an old version of PortAudio. 

Having separate PRs also makes it easier to accept a bug fix PR as a late change before a release and then defer the refactoring PR to after the release, which is less risky.

This separation of PRs is pretty common at companies that are maintaining large and mature code bases. It is standard practice at companies like Google/Android. I know this can seem tedious. But we are in the "move slow and don't break things" stage of development with PortAudio. :-)

2025-03-24 23:13 UTC, RossBencina commented
Bugfix merged as #1008

2025-03-24 23:56 UTC, RossBencina commented
We've decided to pass on the no-behavioral-change rewrite of the `CalculateBufferSettings()` calculation at this time.

2025-03-24 23:56 UTC, closed without merging