Implemented Int32_To_UInt8_Dither
PortAudio/portaudio pull request #841
Opened 2023-09-21 14:55 UTC by ngoiyaeric

Implemented a method to convert data from int32_To_UnInt8_Dither. Port audio did not offer 32bitTriangularDither so I used the available 16bitTriangularDither. Would like to know how to test this code and how to check if it is implemented correctly. The build for port audio works with these changes.

2023-09-22 22:35 UTC, RossBencina commented
Thanks for this. I'm not sure that you have the dither scaling factor correct, could you provide a rationale please?

Running the following tests should be sufficient:

- https://github.com/PortAudio/portaudio/blob/master/test/patest_dither.c
- https://github.com/PortAudio/portaudio/blob/master/test/patest_converters.c

2023-09-23 05:37 UTC, ngoiyaeric commented
Hi, thanks for the corrections. I made the code changes you have suggested. What dynamic range code should I expect after running test/patest_converters for the i32 to ui8 conversions, what logic should I use to generalize this indicator across various conversion tests.

2023-10-06 23:10 UTC, philburk requested changes
The new math looks good.
But the CI found some trailing whitespace:

error: src/common/pa_converters.c(1016) trailing whitespace:
b'    unsigned char *dest =  (unsigned char*)destinationBuffer; '
error: src/common/pa_converters.c(1021) trailing whitespace:
b'       '
error: src/common/pa_converters.c(1028) trailing whitespace:
b'        dest += destinationStride; '

2023-10-06 23:12 UTC, RossBencina commented
> What dynamic range code should I expect after running test/patest_converters for the i32 to ui8 conversions

Same as other ui8 conversions I guess.

Could you paste the output of this test here please and we'll scratch our heads about it:

https://github.com/PortAudio/portaudio/blob/master/test/patest_converters.c

2023-10-08 05:55 UTC, ngoiyaeric commented
> > What dynamic range code should I expect after running test/patest_converters for the i32 to ui8 conversions
> 
> Same as other ui8 conversions I guess.
> 
> Could you paste the output of this test here please and we'll scratch our heads about it:
> 
> https://github.com/PortAudio/portaudio/blob/master/test/patest_converters.c

Hi, 
When I run this command 
gcc -l/portaudio/src/common/ patest_converters.c -o your_output_executable -lm -lportaudio
to test the module, I get this error. 
patest_converters.c:53:10: fatal error: 'pa_converters.h' file not found
#include "pa_converters.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.

Any Ideas how I could fix it?

2023-10-08 08:03 UTC, dmitrykos commented
@ngoiyaeric it depends on how `src/common` folder is related to the path from which you are running GCC build command. If you are running GCC build from inside `portaudio` folder then it would be `-Isrc/common`, if from outside but `portaudio` folder is not in the root of the storage then `-Iportaudio/src/common` and so on.

2023-10-08 14:48 UTC, ngoiyaeric commented
> @ngoiyaeric it depends on how `src/common` folder is related to the path from which you are running GCC build command. If you are running GCC build from inside `portaudio` folder then it would be `-Isrc/common`, if from outside but `portaudio` folder is not in the root of the storage then `-Iportaudio/src/common` and so on.

hi, this does not remedy the issue, the same error is still thrown.

2023-10-08 15:21 UTC, dmitrykos commented
@ngoiyaeric in any case GCC is struggling to locate `pa_converters.h` in your build configuration, it is the only reason. To avoid dealing with compiler configuration directly you could try building `patest_converters` via CMake generated build project.

2023-12-07 09:33 UTC, dmitrykos commented
@ngoiyaeric have you managed to test your implementation? Also this commit (https://github.com/PortAudio/portaudio/pull/841/commits/273c99101954004ff01f93d5f50423b379c21bed) has to be removed from PR.

2024-11-25 23:57 UTC, RossBencina commented
We'd like to see this tested and finalised but given the lack of input, we're not going to hold up the next milestone release for this. We can revisit if someone steps up to fix it.

2024-11-25 23:57 UTC, philburk requested changes

2024-11-25 23:57 UTC, philburk commented on .github/workflows/codesee-arch-diagram.yml
> +# This workflow was added by CodeSee. Learn more at https://codesee.io/
This file should be removed from this PR.
It is unrelated to the purpose of the PR.

2024-12-19 23:11 UTC, philburk commented on src/common/pa_converters.c
>      (void)ditherGenerator; /* unused parameter */
Remove this line. Used on line: 1022.

2024-12-19 23:14 UTC, RossBencina commented
Closing as incomplete / abandoned. We can't merge this as-is and there's been no response from the contributor for over one year.

2026-08-06 12:57 UTC, closed without merging