Adding test to resolve Issue 201
PortAudio/portaudio pull request #844
Opened 2023-10-02 13:11 UTC by Vimal-Krishna

Adding a new test - patest_enumerate_default_latency

Outputs in this format to the cmd line:
```
| X |  42 |  == 1 - LG HDR 4K (AMD High Definition Audio Device) [Loopback] == | Windows WASAPI |   0.0100 |   0.0030 |   0.0000 |   0.0000 |

|   |  68 |  == Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free AG Audio%0;(HC 2000BNC)) == | Windows WDM-KS |   0.0853 |   0.0100 |   0.0853 |   0.0100 |
```

Included the '==' markdown to disable textile formatting within the name field so that special characters like @ do not cause a formatting issue.

<img width="778" alt="image" src="https://github.com/PortAudio/portaudio/assets/11667554/5a1795e4-805d-4846-ae19-a78f21a9b7f7">

Tested the output on https://textile-lang.com/ 

<img width="842" alt="image" src="https://github.com/PortAudio/portaudio/assets/11667554/6d24be05-5e40-486c-9041-f2bbabb67cbc">

2023-10-06 23:00 UTC, RossBencina reviewed
Thankyou! I've added some feedback for your consideration.

2023-10-06 23:02 UTC, philburk requested changes
Thanks for adding this new test program. Looks great!
Just some minor suggestions.

2023-10-06 23:02 UTC, philburk commented on test/patest_enumerate_default_latency.c
> +        printf(" == ");
```suggestion
        printf(" == %s == | ", deviceInfo->name);
```

2023-10-06 23:03 UTC, RossBencina commented
Please fix the compilation errors in CI too.

2023-10-16 01:16 UTC, Vimal-Krishna commented
Thanks for the feedback folks! I think the CI issues should be fixed as well. Let me know if the headers are ok.
(snipped to show entries with 'X')

<img width="700" alt="image" src="https://github.com/PortAudio/portaudio/assets/11667554/0493b976-3984-4e94-876f-ce498f03e624">

2023-11-03 22:00 UTC, RossBencina commented
Thanks this is looking good. The only thing I'm thinking is that it's a bit hard to interpret the 0.0000 entries because we can't see whether it's an input-only or output-only device where 0 is correct, or whether it's a bad value.

What do you think about adding another column `Input/Output Channels` with the channel counts for example `2/0` for a stereo input-only device.

2023-11-11 02:39 UTC, Vimal-Krishna commented
> Thanks this is looking good. The only thing I'm thinking is that it's a bit hard to interpret the 0.0000 entries because we can't see whether it's an input-only or output-only device where 0 is correct, or whether it's a bad value.
> 
> What do you think about adding another column `Input/Output Channels` with the channel counts for example `2/0` for a stereo input-only device.

Yes, seems like a useful addition. I can make the change this weekend. How about we put in a value like N/A instead of 0.0000 for the output latency of an input-only device? And also exclude it when deciding if a device needs the 'X' marker. So the 'X' s will still be the only thing to look for when looking at the report.

2023-11-11 14:08 UTC, Vimal-Krishna commented
Devices 12 to 23 had an X marker before. Now they don't since the channel count is zero for either input or output.
![textile-lang com_](https://github.com/PortAudio/portaudio/assets/11667554/7882f15c-b420-4bd8-8a04-6c774878c118)

2023-11-17 22:58 UTC, RossBencina reviewed
LGTM just going to merge these tweaks myself.

2023-11-17 22:58 UTC, RossBencina commented on test/patest_enumerate_default_latency.c
> +    @brief List available devices in table format
```suggestion
    @brief List default latencies of available devices in table format
```

2023-11-17 22:58 UTC, RossBencina commented on test/patest_enumerate_default_latency.c
> +
```suggestion

```

2023-11-17 22:58 UTC, RossBencina commented on test/patest_enumerate_default_latency.c
> +    printf("|_. Default Latency Zero? |_. Device Number |_. I/O Channels |_. Device Name |_. Host API |_. Default High Input Latency |_. Default Low Input Latency |_. Default High Output Latency |_.
```suggestion
    printf("|_. Bad Default Latency? |_. Device Number |_. I/O Channels |_. Device Name |_. Host API |_. Default High Input Latency |_. Default Low Input Latency |_. Default High Output Latency |_. Default Low Output latency |\n");
```

2023-11-17 23:00 UTC, RossBencina approved these changes

2023-11-17 23:01 UTC, philburk approved these changes

2023-11-17 23:10 UTC, merged

2023-11-17 23:11 UTC, philburk commented
@Vimal-Krishna - Thanks for this contribution. The code looked very nice. We appreciate you closing this old issue from 2011.

2023-11-17 23:48 UTC, Vimal-Krishna commented
@RossBencina @philburk 
Thank you! I enjoyed working on it. I hope to continue working on the project. 🙂